apiVersion: v1
kind: Service
metadata:
  name:  kubeapp-rtp-service
  namespace: kubeapp
spec:
  type: NodePort
  selector:
    app: kubeapp-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
